#ifndef FOUNDATION_MEMORY_TLSFALLOCATOR_FORWARD_HDR
#define FOUNDATION_MEMORY_TLSFALLOCATOR_FORWARD_HDR

#include <Foundation/Memory/Allocators/Advanced/TLSFAllocator.hpp>

#endif // FOUNDATION_MEMORY_TLSFALLOCATOR_FORWARD_HDR
